@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR
skinparam classFontSize 13

Package Model <<Rectangle>>{
Interface ReadOnlyAddressBook <<Interface>>
Interface ReadOnlyCountdown <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface ReadOnlyShortcut <<Interface>>
Interface Model <<Interface>>
Class AddressBook
Class Countdown
Class Shortcut
Class ReadOnlyAddressBook
Class ReadOnlyCountdown
Class ReadOnlyShortcut
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs


Class UniquePersonList
Class Person
Class Address
Class Email
Class Name
Class Phone
Class Tag

Class LocalDate
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook
Countdown .up.|> ReadOnlyCountdown
UserPrefs .up.|> ReadOnlyUserPrefs
Shortcut .up.|> ReadOnlyShortcut

ModelManager .up.|> Model
Model .down.> ReadOnlyUserPrefs
Model .down.> ReadOnlyAddressBook
Model .down.> ReadOnlyCountdown
Model .down.> ReadOnlyShortcut

ModelManager -down-> "1" AddressBook
ModelManager -down-> "1" Countdown
ModelManager -down-> "1" UserPrefs
ModelManager -down-> "1" Shortcut

AddressBook *--> "1" UniquePersonList
Countdown *--> "1" LocalDate
UniquePersonList --> "~* all" Person
Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Address
Person *--> "*" Tag

Name -[hidden]right-> Phone
Phone -[hidden]right-> Address
Address -[hidden]right-> Email

ModelManager -->"~* filtered" Person
@enduml
