@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Interface UserPrefsStorage <<Interface>>
Class JsonUserPrefsStorage
}

Interface Storage <<Interface>>
Class StorageManager

package "AddressBook Storage" #F4F6F6{
Interface AddressBookStorage <<Interface>>
Class JsonAddressBookStorage
Class JsonSerializableAddressBook
Class JsonAdaptedPerson
Class JsonAdaptedTag
}

package "Countdown Storage" #F4F6F6 {
Interface CountdownStorage <<Interface>>
Class JsonCountdownStorage
Class JsonSerializableCountdown
Class JsonAdaptedDate
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" AddressBookStorage
StorageManager -up-> "1" CountdownStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> AddressBookStorage
Storage -left-|> CountdownStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonAddressBookStorage .up.|> AddressBookStorage
JsonCountdownStorage .up.|> CountdownStorage
JsonAddressBookStorage ..> JsonSerializableAddressBook
JsonCountdownStorage ..> JsonSerializableCountdown
JsonSerializableAddressBook --> "*" JsonAdaptedPerson
JsonSerializableCountdown --> "1" JsonAdaptedDate
JsonAdaptedPerson --> "*" JsonAdaptedTag

@enduml
