@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

package Storage{
Interface Storage <<Interface>>
Class StorageManager

package "AddressBook Storage" #F4F6F6{
Interface AddressBookStorage <<Interface>>
Class JsonAddressBookStorage
Class JsonSerializableAddressBook
Class JsonAdaptedPerson
Class JsonAdaptedTag
}

package "Countdown Storage" #F4F6F6 {
Interface CountdownStorage <<Interface>>
Class JsonCountdownStorage
Class JsonSerializableCountdown
Class JsonAdaptedDate
}

package "UserPrefs Storage" #F4F6F6{
Interface UserPrefsStorage <<Interface>>
Class JsonUserPrefsStorage
}

StorageManager .up.|> Storage
StorageManager -left-> "1" AddressBookStorage
StorageManager -down-> "1" CountdownStorage
StorageManager -right-> "1" UserPrefsStorage

Storage -down-|> UserPrefsStorage
Storage -down-|> AddressBookStorage
Storage -down-|> CountdownStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonAddressBookStorage .up.|> AddressBookStorage
JsonCountdownStorage .up.|> CountdownStorage
JsonAddressBookStorage ..> JsonSerializableAddressBook
JsonCountdownStorage ..> JsonSerializableCountdown
JsonSerializableAddressBook --> "*" JsonAdaptedPerson
JsonSerializableCountdown --> "1" JsonAdaptedDate
JsonAdaptedPerson --> "*" JsonAdaptedTag

@enduml
