@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

package Storage{
Interface Storage <<Interface>>
Class StorageManager

package "AddressBook Storage" #F4F6F6{
Interface AddressBookStorage <<Interface>>
Class JsonAddressBookStorage
Class JsonSerializableAddressBook
Class JsonAdaptedPerson
Class JsonAdaptedTag
}

package "Countdown Storage" #F4F6F6 {
Interface CountdownStorage <<Interface>>
Class JsonCountdownStorage
Class JsonSerializableCountdown
Class JsonAdaptedDate
}

package "UserPrefs Storage" #F4F6F6{
Interface UserPrefsStorage <<Interface>>
Class JsonUserPrefsStorage
}

package "Shortcut Storage" #F4F6F6{
Interface ShortcutStorage <<Interface>>
Class JsonShortcutStorage
Class JsonSerializableShortcut
Class JsonAdaptedShortcut
}

StorageManager .up.|> Storage
StorageManager -down-> "1" AddressBookStorage
StorageManager -down-> "1" CountdownStorage
StorageManager -down-> "1" UserPrefsStorage
StorageManager -down-> "1" ShortcutStorage

Storage -down-|> UserPrefsStorage
Storage -down-|> AddressBookStorage
Storage -down-|> CountdownStorage
Storage -down-|> ShortcutStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonAddressBookStorage .up.|> AddressBookStorage
JsonCountdownStorage .up.|> CountdownStorage
JsonShortcutStorage .up.|> ShortcutStorage
JsonAddressBookStorage ..> JsonSerializableAddressBook
JsonCountdownStorage ..> JsonSerializableCountdown
JsonShortcutStorage ..> JsonSerializableShortcut
JsonSerializableAddressBook --> "*" JsonAdaptedPerson
JsonSerializableShortcut --> "*" JsonAdaptedShortcut
JsonSerializableCountdown --> "1" JsonAdaptedDate
JsonAdaptedPerson --> "*" JsonAdaptedTag

@enduml
