@startuml
!include style.puml
show members
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam DefaultFontSize 13

title Commands

package "" {
    object "__undo:UndoCommand__" as Undo1
}

Undo1 : prevCommand = null
@enduml
